name: Docker PHP MySQL App CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build containers
      run: docker-compose build

    - name: Run containers
      run: docker-compose up -d

    - name: Test app
      run: curl -I http://localhost:8000 || true
